pipeline {
    agent any 

    options {
        disableConcurrentBuilds()
    }

    stages {
        stage("Build") {
            steps { buildApp() }
        }
    
        stage("Deploy - Dev") {
            steps { deploy('dev') }
        }
    }
}

//Steps

def buildApp() {
    def containerName = ''
    def port = ''

    if ("${envirmonment}" == 'dev') {
        containerName = "app_dev"
        port = "8888"
    }
    else {
        println "Environment is not valid"
        System.exit(0)
    }

    sh "docker ps -f name=${containerName} -q | xargs --no-run-if-empty docker stop"
    sh "docker ps -a -f name=${containerName} -q | xargs -r docker rm"
    sh "docker run -d -p ${port}:5000 --name ${containerName} hands-on-jenkins/myapp:${BUILD_NUMBER} "
}
